### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by Ejay02** [adi-ray/Web-Development-Projects#3]
I wanna add qr code generator.
Tech Stack: html, css javascript.

**Comment by adi-ray** [comment]
Okay, I am assigning this issue to you !!!

**Comment by Ejay02** [comment]
pls add necessary tags

**Comment by adi-ray** [comment]
Please do these changes:
1. Reply with screenshots / a small demo video .
2. Make necessary changes in README.md .

**Comment by Ejay02** [comment]
1. 
![image](https://github.com/adi-ray/Web-Development-Projects/assets/66236069/b6a21b73-c421-45d4-ab7a-2e3e5d344687)

2. I have a README.md in my QR Folder.  If you meant the parent README.md, that's empty so I'm not sure what changes to make there.

**Comment by adi-ray** [comment]
> 2. I have a README.md in my QR Folder.  If you meant the parent README.md, that's empty so I'm not sure what changes to make there.

yeah, change that README by removing contributing section. I have reviewed some changes in your PR , Let me know if u have done the same.
